#
# ~/.bash_profile
#

[[ -f ~/.bashrc ]] && . ~/.bashrc

export EDITOR=nvim
export VISUAL=nvim
export BROWSER=firefox
export PATH="${HOME}/sw/bin:${HOME}/.local/bin:${HOME}/local/bin:$PATH"
export PATH="$HOME/.local/share/gem/ruby/3.0.0/bin:$PATH"
export CPATH="${HOME}/sw/include:$CPATH"
export LIBRARY_PATH="${HOME}/sw/lib:$LIBRARY_PATH"
export LD_LIBRARY_PATH="${HOME}/sw/lib:$LD_LIBRARY_PATH"
export HISTSIZE=3000
export MOZ_USE_XINPUT2=1

# Automatically start X server if none (or tmux) running
# pgrep 'tmux|startx' || startx

